### ISSUE TITLE
Add animated YMCA

### ISSUE THREAD

**Issue by wendko** [angch/multibot#10]
Y
```
\   /
 \O/ 
  #  
 / \ 
^   ^
```
M
```
 /V\ 
 \O/ 
  #  
 / \ 
^   ^
```
C
```
  r _
 /O/ 
  #  
 / \ 
^   ^
```
A
```
 / \
 \O/
  #
 / \
^   ^
```

Source: https://ascii.co.uk/art/ymca

**Comment by mavjs** [comment]
@wendko - Was bored and made a `YMCA` handler for the bot in #13, not entirely sure if that's what you were looking for though.
